### ISSUE TITLE
[Open Project] Edition on Steve Factory Manager Translation

### ISSUE THREAD

**Issue by 3TUSK** [3TUSK/Temp_LocalizationFile#12]
目前的汉化是我在去年10月完成的。
为了更好地推广SFM这个物流mod，需要对翻译文本重新进行修改。
欢迎提供帮助。

**Comment by 3TUSK** [comment]
If necessary, reopen it for further discussion.

**Comment by bakaxyf** [comment]
https://github.com/hilburn/AdvancedSystemsManager

**Comment by 3TUSK** [comment]
wtf...
