### ISSUE TITLE
request

### ISSUE THREAD

**Issue by ghost** [3TUSK/Temp_LocalizationFile#13]
我能不能在这里放一个项目... (=~ω~=)··· Plant mega pack

**Comment by 3TUSK** [comment]
What's up...PMP我不记得有repo诶

**Comment by ghost** [comment]
可以直接提交给作者. 不过你可以看一下它的lang, 觉得有汉化的必要吗ouo...

**Comment by 3TUSK** [comment]
专有名词数量……Binnie's MOD的Extra Trees也是这个情况

**Comment by ghost** [comment]
那些都不是问题, 如果能放PMP的话麻烦帮忙建个文件夹吧... qwq

**Comment by 3TUSK** [comment]
可以，但是我现在在学校… :(

**Comment by ghost** [comment]
那就慢点再建, 谢谢啦w

**Comment by bakaxyf** [comment]
以建 @3TUSK  @autopsychorhythmia

**Comment by ghost** [comment]
感谢~

**Comment by bakaxyf** [comment]
@autopsychorhythmia  可不可以帮忙一起汉化

**Comment by autopsychorhythmia** [comment]
可以, 是我会玩的一定帮忙/w\

**Comment by ghost** [comment]
可以/w\

**Comment by bakaxyf** [comment]
:D

**Comment by 3TUSK** [comment]
Merged into #15
