### ISSUE TITLE
Translation of "Plant mega pack"

### ISSUE THREAD

**Issue by bakaxyf** [3TUSK/Temp_LocalizationFile#16]
Plant mega pack 翻成植物世界？
总觉得和原意有偏差  
@autopsychorhythmia  @3TUSK

**Comment by ghost** [comment]
随便想的一个名字... 改名求意见

**Comment by 3TUSK** [comment]
Mega表示百万
我个人认为可以翻译成超多植物世界
mcbbs有PMP的搬运
@liach

**Comment by ghost** [comment]
改成"超多植物世界"了.
本来觉得汉化植物名没什么用处,今天把汉化文件放进游戏里看了一下觉得效果还不错. =^=

**Comment by 3TUSK** [comment]
Keep going on~

**Comment by 3TUSK** [comment]
没啥问题的话先close了。有需求的话再重新打开。
