### ISSUE TITLE
[Aether II] zh-HanS localization for 1.7.10 and 1.8

### ISSUE THREAD

**Issue by 3TUSK** [3TUSK/Temp_LocalizationFile#17]
https://gildedgames.oneskyapp.com/collaboration/project?id=22338
Anyone has interest?
~~@autopsychorhythmia~~ @SYNDIG1 @bakaxyf 

Things left:
- [X] Port to 1.8
  - [X] Blocks and Items
  - [X] Achievements and their description
  - [X] Gui (TileEntity, Main menu, etc.)
  - [X] Entity names
  - [X] Splash
- [X] Blocks
- [X] Items
- [X] Companion
- [X] Achievements
- [X] Achievements description
- [X] Splash

**Comment by liach** [comment]
@3TUSK https://github.com/gildedgames

**Comment by 3TUSK** [comment]
https://twitter.com/DevAether/status/571471141547581442
@liach

**Comment by liach** [comment]
though that's a nice idea...

**Comment by ghost** [comment]
不错支持 :3

**Comment by 3TUSK** [comment]
等待申请通过

**Comment by bakaxyf** [comment]
然而申请还没过 差评

**Comment by 3TUSK** [comment]
没邮件回复，而且那个页面上也没有加上zh_CN

**Comment by 3TUSK** [comment]
NO FURTHER INFORMATION, HENCE CLOSE THIS ISSUE AND MERGE INTO #52

**Comment by 3TUSK** [comment]
Reopen it cause I AM LATE FOR TRANSLATION

**Comment by 3TUSK** [comment]
https://github.com/WhiteGems/AE2
Translation should based on the version given above, and the translation portal is:
https://gildedgames.oneskyapp.com/collaboration/translate/project/project/22338/language/3#/

**Comment by 3TUSK** [comment]
依然有很多文本散布在各个class里...果然硬编码是本地化里最不可取的方式...

**Comment by 3TUSK** [comment]
Something and something and something... Aether II added whole bunch of things...

**Comment by 3TUSK** [comment]
@bakaxyf 成就翻译完毕，基于繁体中文翻译，并加以一定修正...

**Comment by 3TUSK** [comment]
闪烁标语翻译完毕

**Comment by 3TUSK** [comment]
宠物部分翻译完毕。现在只剩下1.8了...可以考虑复制粘贴——我预先看过翻译内容，基本没有差别。

**Comment by 3TUSK** [comment]
完成。

**Comment by 3TUSK** [comment]
https://gildedgames.oneskyapp.com/collaboration/translate/project/project/50898/language/278#/
进度^
