### ISSUE TITLE
Translation of "Showy Aster"

### ISSUE THREAD

**Issue by bakaxyf** [3TUSK/Temp_LocalizationFile#18]
觉得不应该把Showy Aster翻成紫菀，把Eurybia spectabilis翻成绿顶菊属紫菀
根据https://en.wikipedia.org/wiki/Eurybia_spectabilis 和 http://zh.wikipedia.org/wiki/%E7%B4%AB%E8%8F%80%E5%B1%AC
绿顶菊属与紫菀属同属于紫菀族，这样绿顶菊属紫菀就有点奇怪了
觉得可以参考https://en.wikipedia.org/wiki/Eurybia_spectabilis 中的其他名字来翻译
@autopsychorhythmia  @3TUSK

**Comment by 3TUSK** [comment]
Showy adj.引人注目的
绿顶菊属紫菀在992行：
https://github.com/3TUSK/Temp_LocalizationFile/blob/master/Plant%20mega%20pack/zh_CN.lang#l992

**Comment by 3TUSK** [comment]
Wait. Google搜“Showy Aster”的结果似乎有些奇怪...图片全是紫菀的
然而Eurybia的情况则是一些原本被归类为Aster的植物被发现应该归类于别的属

**Comment by ghost** [comment]
showyaster和spectabilis就翻成紫菀是我没想出来名字, 然后查到Eurybia是绿顶菊属, 就翻译成这样了. <3
其实根据spectabilis可以翻成显目紫菀..

**Comment by 3TUSK** [comment]
orz...

**Comment by 3TUSK** [comment]
Close...? Close.
