### ISSUE TITLE
[AgriCraft] About the crash

### ISSUE THREAD

**Issue by 3TUSK** [3TUSK/Temp_LocalizationFile#19]
@bakaxyf 
如果没有猜错的话，空格代表换行。
在看Botania的翻译时留意到的它的特性。
AgriCraft的代码中似乎也暗示了相似的特性。
请求帮忙测试。
希望这样可以修复crash。

**Comment by bakaxyf** [comment]
经测试没错

**Comment by 3TUSK** [comment]
改日更新lang。
那些英文是我第一次汉化的时候忘记翻译了。
