### ISSUE TITLE
[Question] Vazbee?

### ISSUE THREAD

**Issue by 3TUSK** [3TUSK/Temp_LocalizationFile#26]
如题。
[这是一个Magic Bees（魔法蜜蜂）新加入的蜜蜂的名字。 ](https://github.com/3TUSK/Temp_LocalizationFile/blob/master/Magic_Bees/zh_CN.lang#L444)
理解起来很简单：Vazkii（植物魔法（Botania）作者）+Bee（蜜蜂）。

问题出现：如何翻译？

一般，蜜蜂的名字都是2字，极少数是4字（例子：有些教程中会把[冰河蜂](https://github.com/ForestryMC/Forestry-Localization/blob/master/assets/forestry/lang/zh_CN.lang#L834)称为“冰河世纪蜂”），罕见情况下可以是3字（例子：有些教程中会把[不倦蜂](https://github.com/ForestryMC/Forestry-Localization/blob/master/assets/forestry/lang/zh_CN.lang#L862)称为“不厌倦蜂”）。目前来看所有蜜蜂名字都是2字。
要保持这个不成文的规则...对于这个蜜蜂的名字来说显然是困难的。

特此寻求帮助。

**Comment by UUUii** [comment]
Va魔蜂:p

**Comment by 3TUSK** [comment]
植魔之蜂……
2字要求达成，但是听上去一股怪味……

**Comment by UUUii** [comment]
嗯，植魔蜂我也觉得怪怪，然而Va魔蜂并没有什么意义|･ω･｀)

**Comment by UUUii** [comment]
从另外一个切入角度呢，这种蜜蜂的产物是什么？

**Comment by 3TUSK** [comment]
产lolita（never mind，我去看一下）

**Comment by UUUii** [comment]
为何我查到关于lolita的诠释是萝莉控= =

**Comment by ghost** [comment]
个人认为是个梗的话还是保留英文原名比较好orz

**Comment by 3TUSK** [comment]
[产物真杂。](https://github.com/MagicBees/MagicBees/blob/master/src/main/java/magicbees/bees/BeeProductHelper.java#L339)
灵魂蜂巢（Soul Comb），附加值为9的染料，附加值为9的羊毛，附加值为7的花。
这个蜜蜂名字就是在恶搞Vazkii（植物魔法作者），理由：这个蜜蜂的描述是“This is not a cosplay bee"

**Comment by UUUii** [comment]
就像有个人跑过来严肃的对你说：“这是一只3TBee，这不是演习，这不是在cosplay”:P

**Comment by 3TUSK** [comment]
所以……先保持原文不动好了……

**Comment by 3TUSK** [comment]
插播新闻：[AE2 rv2-stable放出！](http://ae-mod.info/docs/rv2/release-notes/)

**Comment by UUUii** [comment]
!!!god!

**Comment by bakaxyf** [comment]
~~lolita不是棒棒糖吗~~

edit: 请无视 记错

**Comment by UUUii** [comment]
lolita有一树梨花压海棠的引申义，便是指老夫少妻的意思，在现代又可以戏称为萝莉控......

**Comment by 3TUSK** [comment]
Lolita--->萝莉，Lolicon--->萝莉控。通常，前者简写为loli。
语出俄裔美国作家纳博科夫的同名小说《洛丽塔》（”Lolita"），改编出的电影中文名即是“一树梨花压海棠”。（来自苏轼的嘲讽？）
（买那本小说前，请三思…）
（Edit: 萝莉控是病，得治……）
说那个蜜蜂产萝莉，其实也是低端玩梗……

xyf对"Vazbee"又有何看（高）法（论）？

**Comment by bakaxyf** [comment]
如果硬要翻的话 音译吧

**Comment by 3TUSK** [comment]
仔细考虑了下音译……
1.个人感觉不妥……
2.Vazbee应该有3个音节（syllable）（Va-zi-bi），如何压缩为两个………

**Comment by bakaxyf** [comment]
干嘛一定要压成两个字呢

**Comment by bakaxyf** [comment]
@crafteverywhere 请求帮助

**Comment by 3TUSK** [comment]
且看现在的蜜蜂名称汉化，都是两个字……（含Binnie's MOD和Magic Bees）。就是这么简单…

**Comment by crafteverywhere** [comment]
Vazkii是波兰人，比较难查到其id的出处，不妨音译。
如果音译的话考虑Vaz部分的音节即可。例如瓦兹蜂。
觉得不必过分纠结这种问题，毕竟出处一目了然。

> 至于纳博科夫那本小说，国内流行的几个版本翻译得都挺差。

植魔蜂不推荐，原因是植物魔法这个译名已经是意译了。

**Comment by liach** [comment]
@crafteverywhere Vazkii 是葡萄牙的好不好……asiekierka才是波兰人，而且这个蜜蜂……看看是不是粉色的，据MysteriousAges说有种粉色的蜜蜂vazkii会喜欢……估计是这么来的。

**Comment by crafteverywhere** [comment]
唔。那我记错了233。Anyway，我觉得音译就好。不必要过分在意。

**Comment by 3TUSK** [comment]
Vazkii有说过是根据他自己的名字改出来的……
引用来源是他博客首页……?

**Comment by 3TUSK** [comment]
@liach 被你说中了，那个蜜蜂应该就是粉色的，对应16进代码应该是FF6B9C，另外值得注意的是Botania联动的蜜蜂都涉及到一个静态int常量`BOTANIA = 0xFFB2BB`，对应结果是另外一种粉色
参考：https://github.com/MagicBees/MagicBees/blob/master/src/main/java/magicbees/bees/BeeSpecies.java#L303

**Comment by 3TUSK** [comment]
在没有合适的翻译之前，为保留原文含义，暂时不翻译"Vazbee"。
一旦有合适翻译，则再重新打开Issue进行讨论。

**Comment by 3TUSK** [comment]
#39 @claybiockiller

**Comment by 3TUSK** [comment]
Close this issue without prejudice due to [this pull request](https://github.com/MagicBees/MagicBees/pull/112). 
Although it doesn't mean it is discouraged, phonically translating proper noun (i.e. certain abbreviations (except GT, Greg--->格雷 due to GregTech--->格雷科技), modders' names, make-up term, untranslated term/jargon/terminology stuff, et certra) _is not encouraged_ in a Minecraft mod's translation, because it may cause the missing of extra meaning born by the word itself.
