### ISSUE TITLE
[Open Project]Immersive Engineering Translation

### ISSUE THREAD

**Issue by 3TUSK** [3TUSK/Temp_LocalizationFile#28]
Shoule we put its zh_CN file here to continue working on that, or working separately...?
@bakaxyf

**Comment by 3TUSK** [comment]
Cell phone is no power.
Next time I might set up a IRC channel...

**Comment by bakaxyf** [comment]
直接pull request到作者那吧

**Comment by 3TUSK** [comment]
Well done.

**Comment by bakaxyf** [comment]
https://github.com/bakaxyf/IE-Simplified-Chinese-Localization
@3TUSK

**Comment by 3TUSK** [comment]
orz……从来没注意到fork的也可以改名

**Comment by 3TUSK** [comment]
@bakaxyf 有空看下匠魂的新手册……

Edit: 打算试着汉化一下xml格式的文本，熟悉一下xml...

**Comment by 3TUSK** [comment]
Immersive Engineering has officially released with a whole bunch of new language terms. Were able to hold the file here, network of IE would not be a mess.
Reopen this issue in case of localization need.

**Comment by 3TUSK** [comment]
BTW, keep in mind, AS ACCURATE AS POSSIBLE. If necessary, try to pm Blu for details of localization.

**Comment by 3TUSK** [comment]
Last barrier: something wrong with my fork. <s>Waiting for CannonFotter.</s>

@CannonFotter Thank you very much, but I created BluSunrize/ImmersiveEngineering#164.

This issue should be closed as long as zh_CN.lang get merged, and all related files here _shall_ be removed at that time.
Going to reform this repo.

**Comment by 3TUSK** [comment]
Merged. Close #28.

**Comment by 3TUSK** [comment]
Just added a label for categorizing issues.
