### ISSUE TITLE
[Discussion] Translation of "Craft" in Applied Energistics

### ISSUE THREAD

**Issue by bakaxyf** [3TUSK/Temp_LocalizationFile#31]
现在AE中"Craft"的翻译是合成
但“Craft”并不只有合成的意思
如熔炼、粉碎、压缩、提取  等用其他设备的加工

问：
是否有改动的必要？
如果需改动要改成什么？

**Comment by 3TUSK** [comment]
加工（Processing）（喷）

Edit: Never mind this reply...

**Comment by bakaxyf** [comment]
@ExtraMeteorP  @UUUii  @IamAchang
@crafteverywhere @autopsychorhythmia 
@liach @sb023612  @Mrkwtkr

**Comment by 3TUSK** [comment]
开始着手寻找合适翻译。

**Comment by 3TUSK** [comment]
@bakaxyf @UUUii 
"'Craft' is like to make something from the scratch, or like something for decoration, or it can refer to a vehicle." ---From my teacher

Edit:并非准确记录，只是大概转述

**Comment by 3TUSK** [comment]
Assign invisibly to @bakaxyf .

**Comment by Mrkwtkr** [comment]
把所有craft对应的处理过程列出来看看。。反正我是机械制造专业的，说不定能想到什么。

**Comment by bakaxyf** [comment]
![wc9 2080f v bghaw7h t1](https://cloud.githubusercontent.com/assets/10368307/11324085/5c9db8c8-9161-11e5-8101-2fc8f0ed00e6.png) 这... 
基本上所有的处理都可以用AE吧

**Comment by 3TUSK** [comment]
取决于你的想像力。
@Mrkwtkr 翻译完格雷科技的wiki结果是，有这么几个词和craft意思相近：recipe（合成配方）、process（加工）、carry out（取出）、（未完待续）

**Comment by 3TUSK** [comment]
Result: keep using `Craft`, because everyone has no question on it.

Edit: This question has ended and please do not talk about again if _unnecessary_
