### ISSUE TITLE
[Important] Reorganise this repository

### ISSUE THREAD

**Issue by 3TUSK** [3TUSK/Temp_LocalizationFile#44]
Inspired by [this](https://github.com/Adaptivity/LocalizationsForMCFMods), I decided to pack all of the files into one resource pack, in case when players really need latest translation.

Tasks list:
- [X] `pack.mcmeta`
- [X] `pack.png`
- [X] `../assets/`
- [X] `../assets/[insert mod internal name]/lang` (For all mods)
- [X] Clean up, including not limited in update, remove, et cetera...
- [X] New introduction!

DO NOT TOUCH `Resourcepack` branch, until merged. Thanks for your understanding.

(I don't think I can merge the branch.)

**Comment by CannonFotter** [comment]
Wow!
