### ISSUE TITLE
Translation of "Kinetic Generator"

### ISSUE THREAD

**Issue by 3TUSK** [3TUSK/Temp_LocalizationFile#5]
可用选择:
1.“发生机”
2.“发生器”
目前文本中不统一，需要考虑统一问题

**Comment by bakaxyf** [comment]
发生器一票

**Comment by liach** [comment]
发生机一票

**Comment by 3TUSK** [comment]
@bakaxyf @liach 
加一个可用选择，
3.X动机，其中X代表能量来源，例如Electirc Kinetic Generator = 电动机
这个翻译由@Mrkwtkr 提出

**Comment by liach** [comment]
还是3好

**Comment by Mrkwtkr** [comment]
。。。

**Comment by bakaxyf** [comment]
风动机
蒸汽机
水...
不别扭吗

**Comment by 3TUSK** [comment]
@bakaxyf 水轮机...? 产EU的肯定还是"水力发电机"

**Comment by 3TUSK** [comment]
@bakaxyf @liach @Mrkwtkr 
不知道效果如何...

**Comment by 3TUSK** [comment]
第二次修改...
@bakaxyf @liach @Mrkwtkr Time will tell.
