### ISSUE TITLE
[Open Project][Challenge-Accepted][Finished!] List of unlocalized mods

### ISSUE THREAD

**Issue by 3TUSK** [3TUSK/Temp_LocalizationFile#52]
(Removed unrelated stuff)
Here is a list of mods demanding Chinese(Simplified) localization. Unfinished, and it will be our long-term plan.

Checklist:
- [X] Aether II Note: move back to #17 
- [X] AM2 (review needed)
- [X] IC2CA (review needed)
- [X] LP 
- [X] OC
- [X] PnC (`https://github.com/MineMaarten/PneumaticCraft/pull/842`)
- [X] Sanguimancy

Details:
The form is no longer existed. Everything is totally done. No longer worry!!!!!!!!!!!!!!!!!!!!

**Comment by 3TUSK** [comment]
@bakaxyf
If you have time please consider about those mods.

**Comment by 3TUSK** [comment]
Metallurgy Classic Machine gets localized. Remove it from list.

**Comment by 3TUSK** [comment]
Oh what a hell... @bakaxyf @CannonFotter @UUUii @IamAchang look at what I found today:
https://github.com/AlexFearn/SinoCraft
https://github.com/hypercross/SinoCraft
Seriously? They have never announced as a open-source project. Even nobody have thought on that. 
（总而言之就是为什么不考虑把这坑接下去...）

**Comment by UUUii** [comment]
Do what you want:3..(假装不认识233)

**Comment by 3TUSK** [comment]
I am just kidding.
（刚才那些话全部当屁处理）

**Comment by UUUii** [comment]
Aha...but your cold is cured.

**Comment by 3TUSK** [comment]
True... however I am not good at drawing.
Edit: Immersive Engineering localization finished so it get removed from list.

**Comment by 3TUSK** [comment]
Nuclear Control 2 has caught up its zh_CN localization. Yeah

**Comment by bakaxyf** [comment]
How about [pam's harvestcraft](https://github.com/MatrexsVigil/harvestcraft)?

[sb023612's Localization](https://github.com/sb023612/Localization-Database/tree/master/HarvestCraft/HarvestCraft%201.7.10e)

**Comment by 3TUSK** [comment]
If we can keep touch on her...

**Comment by 3TUSK** [comment]
@bakaxyf 
ChromatiCraft--->彩晶魔法
Chroma (Greek. χρῶμα) =color, colour (English.) 色彩，表明和DyeTrees的联系。
晶，晶体（Crystal）：[ChromatiCraft的水晶相关内容来自GeoStrata，详见repo简介](https://github.com/ReikaKalseki/ChromatiCraft)。
魔法：这mod并不科学，虽然手册是RoC风格的。（实际上分明是DragonAPI的身影...）
你怎么看。（我是对那些看见craft就翻译成“工艺”的人表示无奈了，试问IC，BC，RC都是怎么翻译出来的）

**Comment by bakaxyf** [comment]
How about HQM?
https://github.com/lorddusk/HQM/pull/48/

**Comment by 3TUSK** [comment]
干嘛非得这样链接过去...这样你在他们的`#48`里能看到这里...

**Comment by 3TUSK** [comment]
@bakaxyf 等正式Merge了再说吧。
"Craft"在很多时候都只是一个虚词...以后如果遇到有模组名字里带craft，务必小心。

**Comment by 3TUSK** [comment]
@bakaxyf ~~Tinkers Construct needs language file update?~~  
Definitely TiC needs update: it missing several entries and a whole manual (weaponry).
https://www.reddit.com/r/feedthebeast/comments/3r8nnb/3_years_of_tinkers_construct_development_in_5/

**Comment by 3TUSK** [comment]
Remove Agricraft due to [claybiockiller](https://github.com/claybiockiller), thermal expansion and thermal fundation.

Edit: none of these mods has completed translation; it is because I want to avoid asynchronous work progress that I removed from this agenda.

**Comment by 3TUSK** [comment]
Remove Biome O' Plenty because someone seems to work on that already.

**Comment by 3TUSK** [comment]
@bakaxyf Be prepared: WARNING: Will start to translate botania soon

**Comment by 3TUSK** [comment]
~~@UUUii @bakaxyf @IamAchang @CannonFotter QQ号疑似被盗，暂时无法通过qq联系。如果发现有任何异常均当作qq号已经被盗处理。事态紧急。~~
EMERGENCY STATUS CANCELED

**Comment by 3TUSK** [comment]
Closed #17 and move to here. I need something to show that I am still here though.
Tu fui ego eris. 
Ego Tritusk sum.

**Comment by DSLM** [comment]
QQ被盗？

**Comment by 3TUSK** [comment]
@DSLM 已经找回

**Comment by DSLM** [comment]
那就好，不过顺便解释一下你在FTB把FZ翻成工厂化的原因吧@3TUSK

**Comment by 3TUSK** [comment]
factory n.工厂
-ization 使...化
y和i的发音都是元音/i/（貌似），Quod erat demonstrandum

**Comment by DSLM** [comment]
好吧，这也解释得通

**Comment by IamAchang** [comment]
工厂化算是老翻译了 因式分解是直译.不过两个名字在过去是通用的

**Comment by 3TUSK** [comment]
事实上两个名字互有优劣...如果可以的话，两个名字都用上好了

**Comment by DSLM** [comment]
不过现在好像都在用因式分解了

**Comment by IamAchang** [comment]
因为没多少人玩了

**Comment by DSLM** [comment]
没落的原因呢？

**Comment by IamAchang** [comment]
避免撕逼 拒绝回答

**Comment by DSLM** [comment]
好吧

**Comment by CannonFotter** [comment]
冷静，纠结什么中文译名

**Comment by 3TUSK** [comment]
冷静，考虑下ChromatiCraft的译名@CannonFotter @DSLM @IamAchang

**Comment by 3TUSK** [comment]
冷静，Thaumic Infusion没自带本地化
叫神秘注魔还是神秘注魔方块？个人认同后者。

**Comment by DSLM** [comment]
我倒是比倾向于神秘方块注魔……#(喷)

**Comment by 3TUSK** [comment]
冷静，植物魔法的Narslimmus应该是Narcissus和slime的合成词...
参考：https://en.wikipedia.org/wiki/Narcissus_(mythology)
直接翻译成纳尔斯莱姆斯得了，就像阿卡纳蔷薇一样（喷）

**Comment by 3TUSK** [comment]
@bakaxyf 于是就这样把积压的工作清理没了，贺电

**Comment by 3TUSK** [comment]
Psi.
[需要找一个对魔法科高校劣等生有了解的人...](https://www.reddit.com/r/feedthebeast/comments/41xmpq/new_mod_psi_early_alpha_commentary/)

**Comment by 3TUSK** [comment]
@CannonFotter Someone update Immersive Engineering localization please

**Comment by 3TUSK** [comment]
Thaumic Infusion was finally localized. We will make a legacy support for Thaumci Infusion 1.7.10 based on the existed translation.

**Comment by 3TUSK** [comment]
Added [Sanguimancy](https://github.com/Tombenpotter/Sanguimancy/tree/master/src/main/resources/assets/sanguimancy/lang). zhCN 2 vs 220+enUS, which is _unacceptable_.

**Comment by 3TUSK** [comment]
@IamAchang @CannonFotter 世界再见，挖坑已挖到极致

**Comment by CannonFotter** [comment]
植物魔法。。。

**Comment by 3TUSK** [comment]
还有刚刚开放源码的Psi

**Comment by Joccob** [comment]
咦，我无意间找到了什么...

**Comment by 3TUSK** [comment]
@Joccob Congratulation, you found my to-do list.

**Comment by Joccob** [comment]
Ars magic 2 不是有完整汉化版本么？最近在mcbbs上看到AetherII也有人称完整汉化了...

**Comment by DSLM** [comment]
AM2的确有完整汉化，不过一个问题是似乎没人提交，另外文本好像有些小问题，还有就是有老玩家反应用英文搜构建搜不到（理论上新汉化者还是尽职尽责的，不过老翻译里面英文原文也被放在了翻译后的括号里以便于玩家搜索）

**Comment by DSLM** [comment]
对了，新版本不知道文本改了没

**Comment by Joccob** [comment]
有可能改了，看changelog里面有一项是improved localization

**Comment by 3TUSK** [comment]
@Joccob @DSLM 我对于“汉化”的定义是原生正式（official）汉化。也就是说那些mcbbs上单纯汉化不提交的都不能算的。

**Comment by Joccob** [comment]
好吧，帮忙提交以下就好啦，不过估计要修修改改审核好了再提交

**Comment by 3TUSK** [comment]
@Joccob 尤其是以太II...那个我最不放心，毕竟一代神作竟然到现在都没有原生汉化，太惨了

**Comment by Joccob** [comment]
可以考虑搞一搞，我看atum的文本不多，先接下了

**Comment by 3TUSK** [comment]
CoFH Core gets latest localization. Pull request has sent, and I wonder why nobody notice that very useful command `/cofh`.

Hence, remove CoFH Core from list.

**Comment by 3TUSK** [comment]
Add harvestcraft. No idea why none has ever attempt to contact pam on twitter.

**Comment by GWYOG** [comment]
在联系pam之前我更想先知道下为什么她直接关掉了去年@claybiockiller的PR，这是代表她已经手动加入了潘马斯吗？(照之前德文文本提交的PR看大概是了)不过看起来pam目前最近正忙于1.8.9的开发当中，有没有下一个版本的1.7.10HC都很难说.......
联系pam是要确认这个文本有没有被放入吗？和其他提交文本的人的共识已经达成了吗？

**Comment by 3TUSK** [comment]
@GWYOG From what I understand, this case is similar as this one: `https://github.com/MauveCloud/Ic2ExpReactorPlanner/pull/11`.
That said, pam完全不认识目前既有的三个PR的提交者，所以直接关了。
我的想法是，把目前所有版本的Pam's Harvestcraft的翻译全部找出来然后做一个统一的版本放在这里，然后让@bakaxyf去twitter联系下pam，as Xbony2 said here: `https://github.com/MatrexsVigil/harvestcraft/pull/54#issuecomment-181010031`

**Comment by 3TUSK** [comment]
@GWYOG Also，如果没有1710的HC，那么就是发布这个资源包的时候了——这个Repository就是一个为那些没有自带汉化的mod提供的外挂式语言包（利用原版的resourcepack制作）。

**Comment by GWYOG** [comment]
我想这两个不太一样吧？一个是大段代码的PR，一个是语言文件的PR。后者对于作者几乎不会有负面影响。
从HC的repo看来，大多数PR貌似都是她手动在本地添加进源码中的。这点从那位葡萄牙语本地化者的PR可以推断出来(以及那萌萌的表情)。所以我觉得虽然第一眼看来是她拒绝了@claybiockiller的PR，实则是下一个1.7.10版本的HC我们也许就可以看到官方汉化文件了。

**Comment by 3TUSK** [comment]
@GWYOG Personally speaking, they are _the same_. 我们缺少对外的交流...或许在很长一段时间内，这个大社区没有一个**值得信任**的汉化来源...

**Comment by CannonFotter** [comment]
这点不止pam...比如ic2核电模拟器(新版)的作者就关过pr，原因是“我不认识你你为什么给我pr”

**Comment by GWYOG** [comment]
@CannonFotter  这就是你楼上的楼上的楼上的楼上的链接啊.....
@3TUSK  确实缺少交流....而且不止是对外的交流，还有汉化者内部的交流.....

**Comment by 3TUSK** [comment]
Chinese Minecraft Mod Translation League confirmed（弥天大雾）

**Comment by IamAchang** [comment]
都是散户,交流无力

**Comment by CannonFotter** [comment]
你说这算不算交流？
@IamAchang

**Comment by 3TUSK** [comment]
@IamAchang 于是出现了FTB Wiki Chinese Translation群。
（Wordily Spamming in Github confirmed）

**Comment by Joccob** [comment]
……

**Comment by IamAchang** [comment]
=3需要有人带节奏

**Comment by 3TUSK** [comment]
@Joccob sup

**Comment by Joccob** [comment]
专门建个汉化群? 感觉最后还是会沦为水群…

**Comment by 3TUSK** [comment]
所以说LUX ET FUTURA（光明与未来）嘛。

**Comment by bakaxyf** [comment]
![wc9 2080f v bghaw7h t1](https://cloud.githubusercontent.com/assets/10368307/13151008/12e763be-d6a3-11e5-9f41-69c83332a750.png)

**Comment by Joccob** [comment]
不过要是最后没沦为水群，大家每天在里面讨论些汉化和最新的新闻什么的，感觉还是不错的

**Comment by 3TUSK** [comment]
@Joccob IRC频道吧。避免灌水+没有图片。
@bakaxyf ——>IRC支持者

**Comment by Joccob** [comment]
试一试呗

**Comment by 3TUSK** [comment]
@UUUii @bakaxyf @IamAchang @CannonFotter @GWYOG @Joccob 
www.esper.net #mcmod-get-zh-cn频道已经注册成功，[点此](https://webchat.esper.net/?nick=randomguy&channels=mcmod-get-zh-cn)可直接开始聊天。

**Comment by 3TUSK** [comment]
===========================New Section Started================================
@bakaxyf @DSLM @Joccob @GWYOG 有谁知道如何联系上[前版主sb023612](https://github.com/sb023612/Localization-Database/blob/master/SC2_lang/zh_CN.lang)吗，我需要使用他翻译的Steve's Carts的`zh_CN.lang`。
准确的说，是基于他的翻译做一个最终稿，拿来给这里用。

**Comment by 3TUSK** [comment]
Temporarily remove Tinkers construct, i will consider about legacy support for 1.7.10 later, especially for the manual.

**Comment by 3TUSK** [comment]
Removed Botania. I have updated it yesterday.

**Comment by Joccob** [comment]
sb023612不是在当麻群里么，你去找一下试试能不能联系上

**Comment by 3TUSK** [comment]
@Joccob （我）不在当麻群，如何解决

**Comment by 3TUSK** [comment]
@GWYOG @CannonFotter 有趣的事情出现了：`https://github.com/MauveCloud/Ic2ExpReactorPlanner/issues/13`

**Comment by GWYOG** [comment]
i18n挺好的啊...我还记得之前的旧版核电模拟器(V3)的汉化貌似还是反编译然后修改源码来着的(或者是用mcntools等工具直接修改class文件?)....

**Comment by 3TUSK** [comment]
@GWYOG 问题是，他们不怎么混ic2论坛啊。

**Comment by GWYOG** [comment]
@3TUSK  才发现之前那个PR是IS的人提交的，我真是火星了.....这不禁让我想起前几天希望FTB Utilities加入login系统的那个人，一看就是中国人呐.....

回到正题，作者拒绝PR的第二条理由是

>  there was no prior mention or explanation of the need for these changes in issues or the IC2 forum thread about this app.

所以现在有人来在issue里论述i18n的重要性了吧.....
这个是向作者请求特性的issue所以比起直接PR代码应该会好一点吧

**Comment by 3TUSK** [comment]
你说这个？
`https://github.com/LatvianModder/FTBUtilities/issues/61`

**Comment by GWYOG** [comment]
嗯，我也觉得FTB Utilities要是能有个login system就完美了，但我突然又想到一个问题：除了中国大陆外，其他地区的服务器有没有使用正版验证而用login插件/mod的?.....

**Comment by 3TUSK** [comment]
@GWYOG 你说正版mod服？感觉很多啊= =

**Comment by GWYOG** [comment]
@3TUSK  正版mod服也用登录插件吗？我不太清楚国外的情况啊=。= 
我就担心国外正版服不使用登录插件/mod，这样FTBU加入这个功能的可能性就小了很多.....
如果这个登录系统真的能被加入FTB Utilities的话那就太好了，这样以后可以完全使用官方服务端开服，再也不需要KCauldron了

**Comment by 3TUSK** [comment]
我怎么记得正版服都是开正版验证啊...

**Comment by GWYOG** [comment]
所以当时我看到这个issue时就猜到他可能也是位中国人了.....(鉴于登录插件对于中国大陆的大批盗版用户们实在太实用了0.0)

**Comment by 3TUSK** [comment]
@GWYOG Then how about [this one](https://github.com/ForgeEssentials/ForgeEssentials)

**Comment by GWYOG** [comment]
看起来挺不错的，但ess插件不包含登录啊(也不包含领地)....
感觉ess最实用的还是tpa指令，不过FTBU有它的升级版本tpl...
相较而言，感觉还是FTBU的功能更加实用些

**Comment by 3TUSK** [comment]
@GWYOG 所有人都无视了CoFH Core的/cofh tpx

**Comment by GWYOG** [comment]
@3TUSK  但这个指令是对某个坐标的传送啊(虽然可以跨维度)，我想玩家在服务器应该更需要tpa这种传送到其他玩家位置的指令. 在服务器中，tpx更像是个给op使用的指令；在单人模式中它的用处可能更大些.
不过Cofh Core的那些指令确实被很多人无视了，感觉许多都挺有用的，比如tps或killall

**Comment by 3TUSK** [comment]
cofh的那个指令可以传送到指定世界的指定玩家处啊。参考某一期Direwolf20的Regrowth。
另外关于RoC手册，建议删了meta-inf再试一次，就像1.5.2或者1.4.6/1.4.7时给Minecraft装forge一样。

**Comment by GWYOG** [comment]
发出来后我才突然想到它应该行的(毕竟原版的tp都可以)，真是囧了
话说meta-inf该删哪个？整个meta-inf文件夹吗？我玩mod是从1.6.2开始的所以并不清楚....

**Comment by 3TUSK** [comment]
整个META-INF直接删掉。这是当年给1.4.6/1.4.7/1.5.2装Forge时必备的一个步骤，后来1.6时有了自动安装器于是就很简单了。
因为所有的SHA-256（还是SHA什么，不管了）都在那个文件夹下，删了以后理应可以暂时避开这个检查，然而散布这个没有META-INF的jar却是违反Reika自己的协议的，所以**这个方法仅供测试用**。

**Comment by GWYOG** [comment]
你试过这样做可行吗？我刚才这样做了后还是崩，事情貌似[更糟了](http://pastebin.com/HtQsBYHm)
这样一删MANIFEST.MF(其中包含SHA-256码)在dragonapi检测时就会直接抛出异常了，不可行啊

**Comment by 3TUSK** [comment]
Apologize, 并没有试过。看来这个防护系统比想象的要严密得多…
well，看样子只能找那个人了。给我一段时间…

**Comment by 3TUSK** [comment]
Remove Steve's Carts, because I get permission to use sb023612's translation.
Mark Advanced Genetics as WIP.

**Comment by Joccob** [comment]
Atum 的汉化做完了，不太懂你这个汉化包的工作原理所以没pr，我放到[这里](https://github.com/Joccob/Random-LocalizationFiles/tree/master/Atum-Journey_Into_The_Sands)了，你到时候自己手动commit一下好了

**Comment by 3TUSK** [comment]
@Joccob 直接发这里啊：https://github.com/TeamMetallurgy/Atum

**Comment by Joccob** [comment]
咦，我以为我pr了呢...sorry, 间歇性失忆

**Comment by 3TUSK** [comment]
Okay, remove Atum: Journey to the Sand. Just sit here and wait for merge.

**Comment by 3TUSK** [comment]
Consider about another possibility: @MrGTout 来翻译Ars Magica吧

**Comment by 3TUSK** [comment]
As a responce to @MrGTout , added IC2 Combo Armor. https://bitbucket.org/Zuxelus/ic2-combo-armors

**Comment by 3TUSK** [comment]
Added Logistics Pipes.

**Comment by 3TUSK** [comment]
https://github.com/3TUSK/TemporaryLocalization/commit/714d427c9dca7199398096190dcd88824bb44215
Removed Advanced Genetics via commit above.

**Comment by 3TUSK** [comment]
Remove Mystcraft, because @DSLM has updated it last november.

**Comment by 3TUSK** [comment]
@bakaxyf https://www.reddit.com/r/feedthebeast/comments/48sa82/will_we_ever_be_rid_of_the_multiple_oreingot/
打算做一个这个mod。长期打算，现在拒绝挖坑，留这里备忘。
另外还有别的mod要汉化吗？（blay09系列暂不收，雾）

**Comment by MrGTout** [comment]
@3TUSK 这坑我不接

**Comment by 3TUSK** [comment]
@MrGTout 喷喷喷

**Comment by 3TUSK** [comment]
Removed Reika's mods, cause they have their own repository;
Removed Pam's harvetsraft, cause I have initially finished it;
Removed TiC, cause there is no demand, and there has been a 1.8 translation floating around in www.mcbbs.net.

**Comment by 3TUSK** [comment]
Archive thingy

> @UUUii @IamAchang @CannonFotter 
> Summon some people for help. I have no _knowledge_ about neither RoC nor ReC.
> 
> <S>Also consider about ElectriCraft and ChromatiCraft.
> Especially ChromatiCraft. Huge challenge for its name, lack of _knowledge_ (expect the lexicon thing), > and the mod itself is known by _few_ players.</S>

**Comment by 3TUSK** [comment]
Removed metallurgy 4. I just updated it.

**Comment by 3TUSK** [comment]
Update something. Use branch wisely.

**Comment by 3TUSK** [comment]
@bakaxyf Time to work! https://gildedgames.oneskyapp.com/collaboration/translate/project/project/22338/language/3
Simply copy and paste, please consider about it.
I'll find an existed `zh_CN.lang` for it.

**Comment by 3TUSK** [comment]
Sanguimancy is no longer worth worrying.

**Comment by 3TUSK** [comment]
Removed OpenComputer. I'd say I need someone to test it.

**Comment by 3TUSK** [comment]
搞定了搞定了搞定了搞定了搞定了，RotaryCraft的汉化终于恢复正常了，RotaryCraft的汉化终于恢复正常了，RotaryCraft的汉化终于恢复正常了！！！

**Comment by 3TUSK** [comment]
@GWYOG @Joccob https://github.com/3TUSK/TemporaryLocalization/blob/master/assets/logisticspipes/lang/zh_CN.lang
Any comments?

**Comment by 3TUSK** [comment]
@MrGTout Your pot. https://github.com/3TUSK/TemporaryLocalization/commit/cf085bb06df9efabd7632d8cf863de5d7ffabd06

**Comment by 3TUSK** [comment]
气动：http://tieba.baidu.com/p/4449444777

**Comment by 3TUSK** [comment]
@GWYOG Reminder:
Comprilla in ExCompressum
-parilla "Small grape vine" in spanish. [Ref.](https://en.wikipedia.org/wiki/Smilax_ornata)

@bakaxyf None cares _Ex Comporessum_

**Comment by 3TUSK** [comment]
![generate](https://cloud.githubusercontent.com/assets/9113033/14694662/aa3f2baa-0738-11e6-927e-7e8a03329d3e.png)
@DSLM @IamAchang @CannonFotter @Joccob

**Comment by 3TUSK** [comment]
Remove Ars Magica 2, I used my own tool and I did it.

**Comment by 3TUSK** [comment]
Ofanix居然是上古卷轴里的龙语...意思是exchange...

**Comment by 3TUSK** [comment]
Well...
`https://github.com/MineMaarten/PneumaticCraft/pull/842`
======END OF THE FINAL BATTLE======

**Comment by Joccob** [comment]
Seems Flaxbeard's Steam Power needs a little update

**Comment by 3TUSK** [comment]
Hell... #62

**Comment by 3TUSK** [comment]
I hereby sincerely announce that this issue has officially closed because of the accomplishment of Aether II 1.7.10 zh-CN localization!
