### ISSUE TITLE
[Pathfinder] 1.8 Forward support?

### ISSUE THREAD

**Issue by 3TUSK** [3TUSK/Temp_LocalizationFile#56]
| Mod name | Viewable-source? | Status |
| --- | --- | --- |
| Plants Mega Pack | No | Pending |
| Charset | [Yes](https://github.com/asiekierka/CharsetMC) | Done |
| ~~Intangible~~ | No | Move to Craft's repository |
| Tinkers Construct | Yes | Review |
| Pam's HarvestCraft | Yes | Pending |
| Immersive Engineering | Yes | Done |

**Comment by 3TUSK** [comment]
@bakaxyf Added Intangible.

**Comment by GWYOG** [comment]
这个issue是1.8.x的to-do list吗？话说现在有人开始汉化intangible了吗？

**Comment by 3TUSK** [comment]
暂时还是一个想名字的阶段。

**Comment by GWYOG** [comment]
其实事情是这样的，几小时前的时候看到贴吧有人在做intangible的教程，就问了问他是否有想法汉化一下，因为汉化和教程统一起来会比较好。不过这儿又有提及intangible，所以就想来问下是否有人已经着手做intangible的汉化了.
BTW，刚才去看了下intangible的文本量，将近1000行感觉一个人不太容易能干完；此外又考虑到intangible的闭源特性，是否有必要开一个intangible的本地化仓库？或是把它放到你这儿？

**Comment by 3TUSK** [comment]
@GWYOG 容我今晚考虑一下...其实还有[另一个选择](https://github.com/crafteverywhere/Craft_Minecraft_Mod_Localization)的。

**Comment by GWYOG** [comment]
嗯，craft菊苣那儿确实挺不错的. 
1.8.9的大型mod里面intangible的文本量比psi或血魔法要多许多，感觉该被提上日程了.

**Comment by GWYOG** [comment]
考虑的结果怎么样了? 贴吧的教程作者也已经把许多的物品名称给汉化好了，[汉化文件在4楼的楼中楼里](http://tieba.baidu.com/p/4353029675)

**Comment by 3TUSK** [comment]
craft的仓库吧。

**Comment by GWYOG** [comment]
嗯,已和[教程作者](https://github.com/Khellendroscn)讲好.

**Comment by 3TUSK** [comment]
@GWYOG 所以到底还是没动静了...

**Comment by GWYOG** [comment]
....

**Comment by 3TUSK** [comment]
@GWYOG 挖坑不填系列，看看能不能做出来
`https://github.com/SlimeKnights/TinkersConstruct/pull/1857#issuecomment-204004841`

**Comment by GWYOG** [comment]
如果Adaptivity回归的话，我想他应该可以很快搞好吧
至于Tic的汉化...几个月之前IS的[gxy17886](https://github.com/gxy17886)做过一份半成品[汉化文本](http://www.mcbbs.net/forum.php?mod=viewthread&tid=534057&extra=page%3D1%26filter%3Dsortid%26sortid%3D1%26searchoption%5B144%5D%5Bvalue%5D%3Dtinker%26searchoption%5B144%5D%5Btype%5D%3D)，不过那时boni还没允许提交lang文件
关于文本的提交，目前我的想法是等boni把TiC手册做完后一并提交给他

**Comment by 3TUSK** [comment]
@GWYOG +1...

**Comment by 3TUSK** [comment]
Immersive Engineering is no longer being worried.

**Comment by 3TUSK** [comment]
1.8 is apparently out-of-date though...

**Comment by 3TUSK** [comment]
Close close close
