### ISSUE TITLE
[HarvestCraft] About HarvestCraft

### ISSUE THREAD

**Issue by claybiockiller** [3TUSK/Temp_LocalizationFile#59]
Dear 3TUSK，
The terms "Paneer" and "Paneer Tikka Masala" are not translated in your localization file of HarvestCraft. I thought those term should translated as "印度奶酪” and “马萨拉印度奶酪“。
你的潘马斯文本中”Paneer“和"Paneer Tikka Masala"未翻译。我认为应当译为“印度奶酪”和“马萨拉印度奶酪”。
Claybiockiller(Github)/Clayblockiller(MCF)/Clayblock(MCBBS)

**Comment by 3TUSK** [comment]
I have resigned from community

**Comment by 3TUSK** [comment]
That said, if you think you're right, open a pull request instead, so that I can keep things clean.

**Comment by CannonFotter** [comment]
要我说，有你用英文写这个issue的时间，不如发个pull request
~~You want me to say, have to use English to write the issue of time, rather than send a pull request
---from YouDao~~
IMO should you were free, you'd better to open a new pull request rather than a new issue --- anonymous

**Comment by claybiockiller** [comment]
Can I fork your repo?
我能不能fork你的这个repo?

**Comment by 3TUSK** [comment]
@claybiockiller None said you cannot. Go ahead.

**Comment by 3TUSK** [comment]
WHAT
Next time I do need add something

**Comment by 3TUSK** [comment]
Close via fd964c291616bf1c5920ac7d8b501c868a109e3c
