### ISSUE TITLE
[Mekanism] Mekanism v9?

### ISSUE THREAD

**Issue by 3TUSK** [3TUSK/Temp_LocalizationFile#61]
https://gist.github.com/3TUSK/1c3b19a8a6ab1fc32864d25be4022db0
I get this from @Mrkwtkr and @sfmiyuki, but the thing is that mek is going to release its v9 version. Is there anyone who still have time to work on that?

@bakaxyf @CannonFotter @GWYOG @IamAchang

**Comment by GWYOG** [comment]
Nope, my schoolwork is really heavy and I may not have enough time for localization until August.
Sorry for that.

**Comment by 3TUSK** [comment]
然后我依旧自己更新上去了...虽然是半吊子。
@GWYOG @Mrkwtkr

**Comment by sfmiyuki** [comment]
本来想让当麻弄的，结果等了一个多月还没消息...我周三下午看下细节然后帮忙看下吧（现在在家没有mekv9的翻译）
@3TUSK @Mrkwtkr @GWYOG

**Comment by 3TUSK** [comment]
Okay......
