### ISSUE TITLE
[Trailblazer of Magnum Opus] 1.9 Support - BetterThanMinecon 16.2 Special Version

### ISSUE THREAD

**Issue by 3TUSK** [3TUSK/Temp_LocalizationFile#65]
~~[Give this issue a background music](https://www.youtube.com/watch?v=lTuer4fddC8&list=PL0XLbzBwjEHI7PKwkaoLdcz4mVqew10LY&index=4)~~

(Note: 
1.This issue is multilingual - at least, bilingual.
2.This issue is verbose.)

[Yes that's it](https://btm.unascribed.com/). Expect the miracle.
Besides I do want to see someone who comes from HK/Macau/TW and is willing to help rewrite them into zh_HK/zh_TW/et cetera. I don't really trust those automatic converters, thus I won't do it on my own.

Please, consider helping us finish them before July 29th (UTC) when BTM16.2 will start!
请所有看到此Issue的同学考虑帮助赶在7月29号前完成下表中所有MOD的简中本地化支持，谢谢！
## Statistics Data

Now there are 2 mods (BetterWithMods, Harvest Festival) left, Roots exclusive. The possibility of we pausing Simplified Chinese support of certain mod(s) still exists.
- Roots - I @3TUSK have heard of another guy who is working on the translation. He also made a repost of Roots. Hence we are waiting for further progress.
- BetterWithMods - we are facing the fact that BetterThanWolves has no common-agreed Chinese translation, and we cant find an expert player of BetterThanWolves in our community for now. 
- Harvest Festival - as it is a mod based on settings of [Harvest Moon](https://en.wikipedia.org/wiki/Harvest_Moon_%28video_game%29), we will be unable to get any significant progress unless we can find someone who are familiar with the original game. 
## Why?

~~[Damn](https://twitter.com/bakaxyf/status/683317258223882240) @bakaxyf~~. I guess it is the best way to show [how hardworking Chinese people are](https://github.com/search?utf8=%E2%9C%93&q=filename%3Azh_CN.lang).
Besides, I plan to hold a panel on BTM16.2. I have submitted the request form, and while I am waiting, this will be part of preparation of panel.
## How?
1. Tracking the [mod booth list](http://btm.asie.pl/16.2)
2. Tracking all mentioned mods
3. Once there is available `en_US.lang` then DO IT!!!
4. Go back to 1. and keep guessing which mod will show up on BTM16.2
## Assignee

| Assignee | Assigned task |
| --: | :-- |
| @3TUSK<sup>1</sup> | Actually Additions, Charset, Forestry |
| @bakaxyf | Any blay09's mod in the list below |
| @CannonFotter | Integrated Dynamics |
| @Glease | Automated Redstone, Open Radio, RFTools, Taam |
| @GWYOG | Harvest Festival |
| @IamAchang | Taam |
| @Meow-J | Totemic |
| @panda2134 | Actually Additions |
| ~~@partial-s~~@ayasaki-hayate | RFTools, DeepResonance, Ender Utilities |
| @qianzha<sup>2</sup> | Blood Magic |
| @TehporP<sup>4</sup> | TechReborn |
| The community<sup>3<sup> | Chisel |

TBA. ~~Im still busy with contacting folks and preparing for my Finals. Yes - Finals.~~
~~Now awaiting those who attends [NCEE](https://en.wikipedia.org/wiki/National_Higher_Education_Entrance_Examination).~~ That's ended, so hype!
Also started to work around permission of usage of several existed translation.
Note 1: aka self-recommendation
Note 2: no idea whether we can get the translation done or not. No guarantee.
Note 3: aka a small group of translators. You don't want someone who know nothing about the English language, right?
Note 4: no guarantee.
## Progress tracking

Terminology:
- ?: Uncertain, a.k.a. citation needed, well-known as "Yes? No? Maybe? Maybe not?"
- N/A: either it's unnecessary to support translation (like blay09's BetterMinecraftChat, there is no need of translation), or there are technical difficulties on supporting localization.
- Ref.: Reference for short
- *: Will be supported by resourcepack, either due to technical difficulties or inactivity of author.
- Lib: This is a "mod o' shared", i.e. a library mod. Any mod marked with this have low possibility to be translated - unless there is necessity. 

Special notes: not all reference links are valid - at least, before pull request being merged. Also, it's not always up to date, but I will try do update as soon as possible.

| Mod | Author | zh_CN? | Ref. | Priority |
| --- | --- | --- | --- | --- |
| MinecraftForge | MinecraftForge Team | Yes | [Ref.](https://crowdin.com/project/minecraft-forge) |  |
| AbyssalCraft | shinoow | Yes |  |  |
| Actually Additions | Ellpeck | Yes | Ref. | Higher |
| Additional Banners | Darkhax | Yes | [Ref.](https://github.com/Darkhax-Minecraft/AdditionalBanners/blob/master/src/main/resources/assets/additionalbanners/lang/zh_CN.lang) | Middle |
| Adobe Blocks 2 | The_Fireplace | N/A |  |  |
| ArmorPlus | sokratis12GR | Yes |  |  |
| asielib | asiekierka, Vexatos | Lib |  |  |
| Autoverse | masa | Yes |  |  |
| Baubles | Azanor | Yes |  |  |
| Better With Mods | Beeto | No |  |  |
| BetterMinecraftChat | blay09 | Yes | [Ref.](https://github.com/blay09/BetterMinecraftChat/tree/1.9.4/src/main/resources/assets/betterminecraftchat/lang/zh_CN.lang) |  |
| BetterThanMinecraft | Aesen 'unascribed' Vismea | N/A |  |  |
| Blame | Aesen 'unascribed' Vismea | N/A |  |  |
| Blood Arsenal | Arcaratus | Yes |  |  |
| Blood Magic | WayofTime | Yes | [Ref.](https://github.com/WayofTime/BloodMagic/blob/1.9/src/main/resources/assets/bloodmagic/lang/zh_CN.lang) | High |
| Bookshelf | darkhax, lclc98 | Yes |  |  |
| BTFU | capitalthree | N/A |  |  |
| Chisel | Half The Modding Community | Yes |  |  |
| Chisels & Bits | AlgorithmX2 | Yes |  |  |
| Chisels & Bytes | Belgabor | Yes |  |  |
| Colossal Chests | rubensworks (aka kroeserr) | Yes |  |  |
| CommonCapabilities | rubensworks (aka kroeserr) | Lib |  |  |
| Conventional | Vexatos | N/A |  |  |
| Conventional Chat | asiekierka, Vexatos | N/A |  |  |
| Cooking for Blockheads | blay09 | Yes | [Ref.](https://github.com/blay09/CookingForBlockheads/blob/1.9/src/main/resources/assets/cookingforblockheads/lang/zh_CN.lang) |  |
| Correlated Potentialistics | Aesen | Yes |  |  |
| Crafting Tweaks | blay09 | Yes | [Ref.](https://github.com/blay09/CraftingTweaks/blob/mc19/src/main/resources/assets/craftingtweaks/lang/zh_CN.lang) | High |
| CraftingCraft | blay09 | Yes | [Ref.](https://github.com/blay09/CraftingCraft/blob/1.9.4/src/main/resources/assets/craftingcraft/lang/zh_CN.lang) |  |
| Cyclops Core | rubensworks (aka kroeserr), immortaleeb (aka _EeB_) | Lib |  |  |
| Dark Utilities | Darkhax | Yes |  |  |
| Deep Resonance | McJty, Elec332 | Yes | [Ref.](https://github.com/McJty/DeepResonance/blob/master/src/main/resources/assets/deepresonance/lang/zh_CN.lang) | High |
| Draconic Evolution | brandon3055 | Yes |  |  |
| Enchiridion | joshie | Lib |  |  |
| Ender IO | HenryLoenwind, tterrag, CrazyPants | Yes | Ref. | High |
| Ender Utilities | masa | Yes |  |  |
| EnderCore | tterrag, CrazyPants | Lib |  |  |
| EnderStorage | ChickenBones, covers1624 | Yes |  |  |
| Engination | Falkreon | Yes |  |  |
| Extra Food | dmf444 | Yes |  |  |
| Fancy Fluid Storage | Lordmau5, maxpowa | Yes |  |  |
| Fire's Random Things | TheFireplace | Yes |  |  |
| Flat Colored Blocks | AlgorithmX2 | Yes | [Ref.](https://github.com/AlgorithmX2/FlatColoredBlocks/blob/1.9.4/src/main/resources/assets/flatcoloredblocks/lang/zh_CN.lang) |  |
| Forestry | mezz | Yes | [Ref.](https://github.com/ForestryMC/Forestry-Localization/blob/mc-1.9/assets/forestry/lang/zh_CN.lang) |  |
| Funnels | shadowfacts | Yes |  |  |
| Harvest Festival | joshie | No. | Ref. | Higher |
| Inductive Automation | CD4017BE | Yes |  |  |
| IndustrialCraft 2 | IC2 Dev Team | Yes | Ref.<sup>1</sup> | Highest |
| Integrated Dynamics | kroeser | Yes |  | High |
| Just Enough Items | mezz | Yes | [Ref.](https://github.com/mezz/JustEnoughItems/blob/1.9/src/main/resources/assets/jei/lang/zh_CN.lang) | High |
| McJtyLib | McJty | Lib |  |  |
| MineTweaker 3 | Stan Hebben | N/A |  |  |
| MIPS for OpenComputers | GreaseMonkey, gamax92, Sangar | N/A |  |  |
| MoarSigns | Gory_Moon | Yes |  |  |
| Mod Name Tooltip | mezz | N/A |  |  |
| More Anvils | TheFireplace | Yes |  |  |
| Nether Essence | The_Fireplace | Yes |  |  |
| NotEnoughWands | romelo333 | Yes | [Ref.](https://github.com/romelo333/notenoughwands1.8.8/blob/1.9/src/main/resources/assets/notenoughwands/lang/zh_CN.lang) |  |
| OC Glasses | marcin212, magik6000 | Yes |  |  |
| OpenComputers | Sangar | Yes | [Ref.](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.9/src/main/resources/assets/opencomputers/lang/zh_CN.lang) |  |
| OpenRadio | XDjackieXD | Yes | [Ref.](https://github.com/XDjackieXD/OpenRadio/blob/1.9.4/src/main/resources/assets/openradio/lang/zh_CN.lang) |  |
| Quark | Vazkii, wiiv | Yes |  |  |
| Random Things | Lumien | Yes |  |  |
| Rarmor | canitzp | Yes |  |  |
| RFTools | McJty | Yes |  |  |
| Roots | Elucent, Leordas | Delayed |  |  |
| Sampler | Player | N/A |  |  |
| ShadowMC | Shadowfacts | Lib |  |  |
| Simple Grinder | Rumaruka | Yes | [Ref.](https://github.com/Rumaruka/SimpleGrinder/blob/MC1.9/resources/assets/simplegrinder/lang/zh_CN.lang) |  |
| Simply Caterpillar | The_Fireplace | Yes |  |  |
| Solar Village | Darkhax | Yes |  |  |
| Soul Shards: The Old Ways | TehNut | Yes | [Ref.](https://github.com/TehNut/Soul-Shards-The-Old-Ways/blob/1.9/src/main/resources/assets/soulshardstow/lang/zh_CN.lang) |  |
| Starvation Ahoy | dmf444 | Yes |  |  |
| TechReborn | modmuss50, Gigabit101, Prospector | Yes | [Ref.](https://github.com/TechReborn/TechReborn/blob/1.9/src/main/resources/assets/techreborn/lang/zh_CN.lang) | High |
| Techy | Tbsc | Yes |  |  |
| The One Probe | McJty | Yes |  |  |
| TIS-3D | Sangar | Yes | [Ref.](https://github.com/MightyPirates/TIS-3D/blob/master-MC1.8.9/src/main/resources/assets/tis3d/lang/zh_CN.lang) |  |
| Totemic | ljfa | Yes | [Ref.](https://github.com/TeamTotemic/Totemic/blob/master/src/main/resources/assets/totemic/lang/zh_CN.lang) | High |
| TrashSlot | blay09 | Yes | [Ref.](https://github.com/blay09/TrashSlot/blob/1.9.4/src/main/resources/assets/trashslot/lang/zh_CN.lang) |  |
| Vanilla Immersion | PaleoCrafter | Yes |  |  |
| WeaponsPlus | sokratis12GR | Yes |  |  |
| YeOldeTanks | shadowfacts | Yes | [Ref.](https://github.com/shadowfacts/YeOldeTanks/blob/1.9/src/main/resources/assets/yeoldetanks/lang/zh_CN.lang) |  |

1: ~~I knew that that translation for IC2exp in 1.8.9 is retrieved from www.mcmod.cn but I do need to double check. This is a reminder - due to IC2's special position in most players' mind, I won't forgive any fatal mistakes.~~ Done. However, it still requires some revision, so submission will be delayed definitely.

**Comment by ghost** [comment]
What do those '?' marks mean..?

**Comment by 3TUSK** [comment]
"?" means "not sure" or "have no idea" as the last "?" in your question. @partial-s

**Comment by ghost** [comment]
So I was thinking there still has some items that could be confirmed as a certain defined status by compare the differences between old and new language files. Such as Chisel, Cooking for Blockheads, and RFTools.

In my opinion.

**Comment by 3TUSK** [comment]
@partial-s I might add IndustrialCraft 2 to the list. Because, [just because](https://twitter.com/asiekierka/status/732160196110356480).

**Comment by ghost** [comment]
Well, I'm unacquainted with IndustrialCraft² now.

**Comment by 3TUSK** [comment]
...
Table is broken.

**Comment by 3TUSK** [comment]
Table repaired, but I will update IC2 - I need that XD

**Comment by 3TUSK** [comment]
shadowfacts/YeOldeTanks#16
Update zh_CN for YeOldeTanks

**Comment by 3TUSK** [comment]
romelo333/notenoughwands1.8.8#1
Update zh_CN for NotEnoughWands

**Comment by 3TUSK** [comment]
asiekierka/CharsetMC#63
Create multiple zh_CN for Charset.

> 。

Edit: Changed to
CharsetMC/Charset-i18n#1

**Comment by 3TUSK** [comment]
TehNut/Soul-Shards-The-Old-Ways#14
Re-create zh_CN for SoulShards-TOW

**Comment by 3TUSK** [comment]
@partial-s 说起来，http://www.mcmod.cn/class/333.html 为什么全是英语，又不是FTB Wiki（不论是gamepedia还是ftbwiki.org）

**Comment by DSLM** [comment]
写的人是直接复制粘贴的吧

**Comment by 3TUSK** [comment]
@DSLM 唉。
另，催更OpenBlock的FTB Wiki翻译，我相信你的Final已经结束了（雾）

**Comment by 3TUSK** [comment]
Rumaruka/SimpleGrinder#7
Update zh_CN for SimpleGrinder...

Edit: further update
Rumaruka/SimpleGrinder#9

**Comment by 3TUSK** [comment]
abecderic/holovm#2
Create zh_CN for HolographicVictoryMonument

**Comment by asiekierka** [comment]
> I guess it is the best way to show how hardworking Chinese people are.

You're competing with the German work ethics of Vexatos here (who has translated literally hundreds of mods over the past 2-3 years). Watch out.

Anyhow, amazing project!

**Comment by 3TUSK** [comment]
@asiekierka But @crafteverywhere is more hardworking than me, to be honest. [Statistic data](https://github.com/search?utf8=%E2%9C%93&q=author%3Acrafteverywhere)

Edit: Also @Mrkwtkr. [Statstics data](https://github.com/search?utf8=%E2%9C%93&q=author%3Amrkwtkr&type=Issues&ref=searchresults)

**Comment by asiekierka** [comment]
More than half of [this](https://github.com/search?utf8=%E2%9C%93&q=author%3AVexatos&type=Issues&ref=searchresults) is translations.

**Comment by 3TUSK** [comment]
> I really want to combine all known Chinese translators' statistic data together.

**Comment by mezz** [comment]
Please add JustEnoughItems to the list https://github.com/mezz/JustEnoughItems/blob/1.9/src/main/resources/assets/jei/lang/zh_CN.lang
I think it's mostly complete though.

**Comment by 3TUSK** [comment]
@mezz Apologize, also added JEI back.

> Anyone knows how to do a booth for JEI?

**Comment by 3TUSK** [comment]
Darkhax-Minecraft/AdditionalBanners#2
Create zh_CN for Add. Banners

> Success of regex. aka. find&replace

**Comment by 3TUSK** [comment]
mezz/JustEnoughItems#281
Update zh_CN for JEI. Long missing update.

> CLA... @mezz I suggest to separate `assets/jei/lang` to another repository, as Forestry does.

**Comment by mezz** [comment]
Keeping another repository for JEI lang is more work, it doesn't change very much. Thanks!

**Comment by 3TUSK** [comment]
jaredlll08/Fluxed-Crystals-3#3
(Re-)Create zh_CN for Fluxed Crystals. I used to have a translation for _Fluxed Crystal_ but that is too bad.

**Comment by 3TUSK** [comment]
https://github.com/3TUSK/TemporaryLocalization/commit/9c00fdb9d5adc331d4149199dbef54f7bad0b33c
Create zh_CN for MoreAnvils. Plan to migrate to [MoreAnvil Repository](https://bitbucket.org/The_Fireplace/more-anvils).

**Comment by 3TUSK** [comment]
heldplayer/MahMeat#1
Create zh_CN for MahMeat

> I know it's too cruel... but Im not allowed to have tears...

**Comment by 3TUSK** [comment]
blay09/TrashSlot#22
Create zh_CN for TrashSlot

> Authored by @bakaxyf

**Comment by 3TUSK** [comment]
blay09/CookingForBlockheads#122
blay09/CookingForBlockheads#123
Update zh_CN for Cooking For Blockheads

> Authored by @bakaxyf
> 122 is for 1.9; while 123 is for 1.9.4. Why not `$ git cherry-pick`. Or just merge 1.9 branch into 1.9.4.

**Comment by 3TUSK** [comment]
blay09/CraftingTweaks#80
blay09/CraftingTweaks#81

> Authored by @bakaxyf 
> Why still updating 1.7.0? That is probably no longer being supported,

**Comment by Rumaruka** [comment]
I need update for new version =)

**Comment by 3TUSK** [comment]
Flaxbeard/Sprockets#2
Create zh_CN for Sprockets

> rush, rush, rush

**Comment by 3TUSK** [comment]
@Rumaruka Updated yesterday. XD

**Comment by Glease** [comment]
XDjackieXD/OpenRadio#11 that's all I could help.

**Comment by 3TUSK** [comment]
Thanks a lot

**Comment by 3TUSK** [comment]
Also... you forget one thing
McJty/RFTools#544
Update zh_CN for RFTools

Wait... @Glease which branch?

**Comment by Glease** [comment]
Uh oh, well, I don't think a commit of one line modified worth mentioning (expect those like openjdk RFR 8148604). It didn't take me more than 1 minute.

--- Original Message ---

**Comment by 3TUSK** [comment]
@Glease But there is a `1.9.4` branch in RFTools. You pushed into `master`. 
Will you ask for `git cherry-pick`?

**Comment by Glease** [comment]
Doesn't really need it. I think partial-s must have done everything for 19x, or did  (s)he?

--- Original Message ---

**Comment by 3TUSK** [comment]
Fair enough...

**Comment by GWYOG** [comment]
Well... As what I said yesterday in #66, dimlet stuffs have totally been moved to RFTools Dimensions. In fact, I have translated this item [3 months ago](https://github.com/McJty/RFToolsDimensions/blob/master/src/main/resources/assets/rftoolsdim/lang/zh_CN.lang#L73), so there is no need to ask `git cherry-pick` for this one. :)

**Comment by Glease** [comment]
CD4017BE/AutomatedRedstone#1 another

--- Original Message ---

**Comment by asiekierka** [comment]
Correlated Potentialistics and Roots were added to the mod list

**Comment by Glease** [comment]
Could you please turn that giant mod list into a file(maybe in a sperate branch)? Then others will be easier to suggest edits.

--- Original Message ---

**Comment by 3TUSK** [comment]
@asiekierka Done
@Glease Host at where... [the wiki](https://github.com/3TUSK/TemporaryLocalization/wiki)? Cause that is open to everyone currently.

**Comment by abecderic** [comment]
Since I don't know if you guys watch the repository, I thought I'd let you know that I've added a few more Strings in need of chinese localization:
https://github.com/abecderic/holovm/blob/master/src/main/resources/assets/holovm/lang/en_US.lang

**Comment by Ellpeck** [comment]
If you actually get the entirety of Actually Additions translated, then wow.
That would be amazing.

**Comment by 3TUSK** [comment]
@Ellpeck Actually I am working around with Actually Addition right now
@abecderic Will take a look today.

**Comment by 3TUSK** [comment]
abecderic/holovm#4
Update zh_CN for HoloVM

**Comment by 3TUSK** [comment]
WayofTime/BloodMagic#779
Long missing update: Update zh_CN.lang for Blood Magic! Authored by qianzha!

**Comment by 3TUSK** [comment]
Lordmau5/FFS#57
Create zh_CN for Fancy Fluid Storage.

> Ok I finally overcame the damnit jet lag. Switch to hard-working mode.
> Today should be the end of NCEE for most of my friends. Hope they can give me a hand.

**Comment by 3TUSK** [comment]
lumien231/Random-Things#86
Create zh_CN for Random Things

> So it's random translation. lol.

**Comment by 3TUSK** [comment]
CharsetMC/Charset-i18n#3
Update zh_CN for Charset.

> ！
> Fullwide exclamation mark.
> Apparently jet lag is still influencing me. I opened an unnecessary pull request.

**Comment by 3TUSK** [comment]
elytra/CorrelatedPotentialistics#21
Create zh_CN for Correlated Potentialistics

**Comment by 3TUSK** [comment]
PaleoCrafter/VanillaImmersion#6
Create zh_CN for Vanilla Immersion

**Comment by 3TUSK** [comment]
Darkhax-Minecraft/Tesla#17
Create zh_CN for Tesla API

> What, Tesla?

**Comment by 3TUSK** [comment]
elucent/Roots#22
Create zh_CN for Roots

> Long time no see.

**Comment by kraineff** [comment]
@3TUSK can you translate https://github.com/xMrVizzy/PlayerStats/tree/1.9.4/localization on zh_CH lang :)

**Comment by 3TUSK** [comment]
@xMrVizzy pull request has opened, please check :)

**Comment by 3TUSK** [comment]
https://github.com/3TUSK/TemporaryLocalization/commit/dd1940f33e8860dd8c36852f90fe7c6f3ae94074
Create zh_CN for Fire's Random Things, merge request will open soon or later.

**Comment by Glease** [comment]
BTM 16.2 site has moved. Please update the link. 

> Though there is a link to the new site on the old page

**Comment by Glease** [comment]
Team-IO/Taam#215 Done.

**Comment by 3TUSK** [comment]
asiekierka/Computronics#203 Done.

> Update zh_CN for Computronics

**Comment by Vexatos** [comment]
Just a note here: This is awesome. I wish there were this many decent German translators ;)

**Comment by 3TUSK** [comment]
@Vexatos Thanks.
Also:
Elecs-Mods/E-Flux#11
Create zh_CN for E-Flux. I'd say multiblock is awesome as well.

**Comment by 3TUSK** [comment]
@partial-s @DSLM @GWYOG @Glease 
问题：
Crafting Table IV如何翻译。[详细信息](http://forum.feed-the-beast.com/threads/craftingtable-iv-the-successor-of-the-famous-craftingtable-iii-mod.95818/)。

> 个人倾向于“改良工作台（第四代）”这样

**Comment by TehporP** [comment]
@3TUSK 4级工作台或者工作台-IV

**Comment by Glease** [comment]
便捷4G工作台(雾)

--- Original Message ---

**Comment by 3TUSK** [comment]
ssblur/ParcelsAndPackages#5
Create zh_CN for Parcels&Packages

**Comment by 3TUSK** [comment]
McJty/TheOneProbe#21
Create zh_CN for TheOneProbe

**Comment by 3TUSK** [comment]
Elecs-Mods/CraftingTable-IV#32
Create zh_CN for CraftingTable-IV

**Comment by 3TUSK** [comment]
amadornes/Framez#45
Create zh_CN for Framez

**Comment by 3TUSK** [comment]
gjgfuj/OAReborn#3
Create zh_CN for OpenAutomation Reborn

**Comment by 3TUSK** [comment]
TeamDmfMM/StarvationAhoy#37
Create zh_CN for Starvation Ahoy

**Comment by 3TUSK** [comment]
maruohon/autoverse#1
Create zh_CN for Autoverse

**Comment by 3TUSK** [comment]
@partial-s 
`item.deepresonance.rcl_module.name=RCL Screen Module`
从Deep Resonance里找到的...完全不知道是什么情况。
另，是否翻译Deep Resonance这个mod名字？打算更新一波了。

**Comment by panda2134** [comment]
Now there're lots of pages of Actually Addition manual to be translated. It's hard work.So if you understand Chinese,feel free to help us. Just comment on this issue.Thanks!
实用拓展的手册还有许多面没翻译，有时间的童鞋们请迅速来帮忙！回复该issue即可。谢谢！

**Comment by Ellpeck** [comment]
It's really awesome that you do this, but I'm still hoping for a time where people actually manage not to misspell the mod's name.
"Actually Additions" :p

**Comment by partial-s** [comment]
@3TUSK 
I suppose that "RCL" is the abbreviation of "Resonating Crystal Liquid". [[1]](https://github.com/McJty/DeepResonance/blob/master/src/main/resources/assets/deepresonance/text/manual.txt#L37)
"Deep Resonance" have already translated as "深度共振" in my last commit [[2]](https://github.com/3TUSK/TemporaryLocalization/blob/rftools/assets/deepresonance/lang/zh_CN.lang#L37), just modify it if you think it's inapposite.

**Comment by 3TUSK** [comment]
@Ellpeck Done. Apologize for ignoring plural.

**Comment by 3TUSK** [comment]
Mod list has updated. Now what we need is just more human resources (i.e. volunteering translators, aka free labor)...

**Comment by Ellpeck** [comment]
I'd totally help. But.. you know. Those chinese letter thingies you have there mean absolutely nothing to me. Sadly, I don't know anyone who speaks chinese either, otherwise I'd bring them here :(

**Comment by 3TUSK** [comment]
@Ellpeck That's why I put Actually Additions on my todo list with highest priority right now :)

**Comment by 3TUSK** [comment]
~~sokratis12GR/ArmorPlus#30~~
~~Update zh_CN for ArmorPlus.~~

> ~~Powered by Official FTB Wiki~~

Edit:
sokratis12GR/ArmorPlus#31
Update zh_CN for ArmorPlus

> This time comes with correct, lastest branch.

**Comment by 3TUSK** [comment]
shadowfacts/Funnels#1
Create zh_CN for Funnels

> Why I think it has been created long ago?

**Comment by 3TUSK** [comment]
Darkhax-Minecraft/Bookshelf#41
Create zh_CN for Bookshelf

**Comment by 3TUSK** [comment]
Belgabor/ChiselsBytes#1
Create zh_CN for Chisel & Bytes

> One line... remember RTG?

**Comment by 3TUSK** [comment]
CyclopsMC/ColossalChests#29
Create zh_CN for Colossal Chest

**Comment by 3TUSK** [comment]
sokratis12GR/WeaponsPlus#5
Create zh_CN for WeaponPlus

> ~~Powered by Official FTB Wiki~~

**Comment by 3TUSK** [comment]
@Joccob If you're free, please consider providing help, I will appreciate it :)

**Comment by sokratis12GR** [comment]
@3TUSK Here is the updated list: https://btm.unascribed.com/mods
And your panel is approved ;) https://btm.unascribed.com/panels

**Comment by 3TUSK** [comment]
@sokratis12GR Thx, also don't you notice that I have updated the list already? XD

**Comment by sokratis12GR** [comment]
Nope xD

**Comment by 3TUSK** [comment]
Vazkii/Quark#83
Update zh_CN for Quark

> ......

**Comment by 3TUSK** [comment]
Darkhax-Minecraft/SolarVillage#3
Create zh_CN for Solar Village

> Imagine a village fulfilled with solar panels.

**Comment by Joccob** [comment]
Amazing project, definitely will help ~

**Comment by Rumaruka** [comment]
i make support for JEI =)

**Comment by 3TUSK** [comment]
@Rumaruka Rumaruka/SimpleGrinder#17
Update zh_CN for Simple Grinder.

> I feel like there is merge conflict floating around...

**Comment by 3TUSK** [comment]
GoryMoon/MoarSigns#21
Update zh_CN for MoarSigns

> 100th comments. Congrats

**Comment by 3TUSK** [comment]
Darkhax-Minecraft/Dark-Utilities#8
Create zh_CN for Dark Utilities

**Comment by 3TUSK** [comment]
TeamDmfMM/Extra-Food#42
@GWYOG Update zh_CN for Extra Food

**Comment by 3TUSK** [comment]
SleepyTrousers/EnderIO#3463
Update zh_CN for EnderIO

**Comment by 3TUSK** [comment]
CD4017BE/InductiveAutomation#13
Create zh_CN for Inductive Automation

GoryMoon/MoarSigns#22
Update zh_CN for MoarSigns

**Comment by 3TUSK** [comment]
McJty/RFTools#606
Update zh_CN for RFTools (1.9.4 ver.)

**Comment by 3TUSK** [comment]
TechReborn/TechReborn#663
Update zh_CN for TechReborn, powered by @TehporP 
WayofTime/BloodMagic#835
Update zh_CN for Blood Magic, powered by @qianzha

> Really, appreciate a lot!

**Comment by 3TUSK** [comment]
TechReborn/TechReborn#665 TechReborn/TechReborn#666
Update zh_CN for TechReborn, powered by @TehporP

**Comment by 3TUSK** [comment]
maruohon/enderutilities#21
Create zh_CN for Ender Utilities, powered by @ayasaki-hayate

**Comment by 3TUSK** [comment]
Tbsc/Techy#13
Create zh_CN for Techy

**Comment by CannonFotter** [comment]
CyclopsMC/IntegratedDynamics#59
Create zh_CN for IntegratedDynamics
@3TUSK @bakaxyf

**Comment by 3TUSK** [comment]
TeamTotemic/Totemic#18 TeamTotemic/Totemic#19
Update zh_CN for Totemic, special thanks to @Meow-J

**Comment by Belgabor** [comment]
@3TUSK Update for Chisels & Bytes with extended translation support is coming, it would be great if you could amend your translation.

**Comment by 3TUSK** [comment]
@Belgabor Belgabor/ChiselsBytes#3 here you go. Sorry for late reply.

**Comment by 3TUSK** [comment]
elytra/Engination#1 
Create zh_Cn for Engination

> Why we localize unreleased mod??? Couldnt really understand

**Comment by 3TUSK** [comment]
canitzp/Rarmor#13
Create zh_CN for Rarmor

**Comment by 3TUSK** [comment]
Arcaratus/BloodArsenal#53
@qianzha Create zh_CN for Blood Arsenal

> Late to record here, again...

**Comment by 3TUSK** [comment]
blay09/BetterMinecraftChat#12
@Meow-J Create zh_CN for BetterMinecraftChat

**Comment by 3TUSK** [comment]
Ellpeck/ActuallyAdditions#156
@panda2134, @JackyWangMislantiaJnirvana, et al Create zh_CN for ActuallyAdditions

> Now... it is the time...

**Comment by 3TUSK** [comment]
Chisel-Team/Chisel#195
Re-Create zh_CN for Chisel (Chisel Team)...

**Comment by 3TUSK** [comment]
blay09/CookingForBlockheads#146

> ...Update? (not on 1.9.4 branch) zh_CN for CookingForBlockheads, so a bit off-topic
> Besides, someone is floating around...?

**Comment by 3TUSK** [comment]
Ok here is probably the final result:
More than 95% (estimated) of those mods have gotten localization support, maybe a bit more or a bit less. I hereby consider this mission as "not fully completed but effective enough".  
Some of localization files are not sent to mod author yet (e.g. IC2-Experimental, Roots, Simple Caterpillar). This will be done soon <sup>TM</sup>. (but, really, once I get seconds of free time.)  
Some of localization support may be outdated (e.g. Quark), but I would like to provide further support if I am available, plus anyone asks for such.  
I am sorry but there are two mods untranslated: BetterWithMods, and Harvest Festival. They are, unfortunately, fall into the "technical difficulties" category. Both of them are based on something that we have **no** existed official documents that is translate/transliterate/[whatsoever way] into Chinese. To be specific, BetterWithMods is a mod that based on BetterThanWolves but there is no complete documentation or tutorial of BetterThanWolves that is written in Chinese (no matter what variant it is); Harvest Festival is a mod based on Harvest Moon series but we neither could find reliable source that can use as reference, nor could find a community member who have played Harvest Moon for a while. I do believe, however, those two of "technical difficulties" will be terminated in the age, as it _is_ a matter of effort.
All translators that have responded to this project have witnessed the birth of miracle. Hope everyone who have read here to enjoy [BetterThanMinecon 16.2.](https://btm.unascribed.com/mods)

~ @3TUSK at 23:42 Jul 27th 2016 UTC+8

Acknowledgement:
@Meow-J @Glease @GWYOG @TehporP @qianzha @CannonFotter @panda2134 @JackyWangMislantiaJnirvana for translation;
Also @IamAchang @bakaxyf @J-swl for consisting support this mission (in translation or in other spiritual ways);
Also @partial-s (the corresponding account has been deleted multiple times) for his (or her? no one knows) coming back of short time, just to help on this project;
Also very special thanks to @asiekierka for posting twitter;
Also very special thanks to anyone who reply here;
Also, special thanks to you who are looking at these words. ~~(No this is not a Touhou reference, believe or not)~~

> Next Phantasm ~

**Comment by 3TUSK** [comment]
If anyone who participates this project but his/her/[insert proper pronoun] name is not listed above, please reply soon and I will add them.

**Comment by asiekierka** [comment]
Good job!

**Comment by 3TUSK** [comment]
Thanks
