### ISSUE TITLE
Repository rename proposal & Guideline rewrite & Migration

### ISSUE THREAD

**Issue by 3TUSK** [3TUSK/Temp_LocalizationFile#70]
* [X] TemporaryLocalization -> ~~Temp-i18n or Temp-g11n? For short sake~~ Done, `Temp-l10n`
* [X] Distinguish i18n and l10n. <sup>Note 1</sup>
* [X] Enforce [Meow-J's guideline](https://github.com/Meow-J/Mod-Translation-Styleguide)
  * [X] Enforce full-width punctuation
  * [X] Transcription rules - I think I need a copy of IPA table
  * [X] Deal with romanized Japanese
  * [X] ***Tone***
* [X] ~~Toolkit contribution guideline~~
  * [X] ~~Lua 5.2 backward compatible? I believe that I have already cover it.~~
  * [X] ~~Coding style convention~~
  * [X] Considering split the toolkit out - 3TUSK/i18n-toolkit#1
* [X] Issue template
  * [X] For i18n/l10n
  * [X] ~~For toolkit~~ - though I think I won't get one, there is still a warning about not accepting issues.
* [X] ~~Consider: A mirror repository on OSChina/Coding?~~ No, we are migrating. This will not be covered this time.
  * [X] ~~Auto-upload process? GitHub's API should be able to do this.~~ Same as above.
* [X] **IMPORTANT**: migrate our `1.10.2` branch to [TartaricAcid's new repository](https://github.com/TartaricAcid/Minecraft-Mod-Language-Package)

See [this](https://en.wikipedia.org/wiki/Internationalization_and_localization) for how complex it is.

Note 1: Consider about the following example (though it is not the best one):
 * Text: When in Rome, do as the Romans do.
 * i18n: 身在罗马，应像罗马人一样做事。 
 * l10n: 入乡随俗。

Issue subject to change.

**Comment by liach** [comment]
I wonder if you are interested in this: https://github.com/Nuchaz/BiblioCraft/tree/master/assets/bibliocraft2/lang

**Comment by 3TUSK** [comment]
None of current supported mods are included in major 1.10.2 packs. The migration can be  automatically considered as done. Issue close.
